/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CandidatesImport } from './routes/candidates'
import { Route as IndexImport } from './routes/index'
import { Route as FormIdImport } from './routes/form/$id'

// Create/Update Routes

const CandidatesRoute = CandidatesImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormIdRoute = FormIdImport.update({
  id: '/form/$id',
  path: '/form/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesImport
      parentRoute: typeof rootRoute
    }
    '/form/$id': {
      id: '/form/$id'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof FormIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates': typeof CandidatesRoute
  '/form/$id': typeof FormIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates': typeof CandidatesRoute
  '/form/$id': typeof FormIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/candidates': typeof CandidatesRoute
  '/form/$id': typeof FormIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidates' | '/form/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidates' | '/form/$id'
  id: '__root__' | '/' | '/candidates' | '/form/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatesRoute: typeof CandidatesRoute
  FormIdRoute: typeof FormIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatesRoute: CandidatesRoute,
  FormIdRoute: FormIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/candidates",
        "/form/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/candidates": {
      "filePath": "candidates.tsx"
    },
    "/form/$id": {
      "filePath": "form/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
